version: "3.8"

services:
  stocks-app:
    container_name: stocks-data
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stocks-db.car422cofz4d.us-east-1.rds.amazonaws.com:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Testdb123-
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
