CREATE TABLE IF NOT EXISTS SYMBOL (
    ID SERIAL PRIMARY KEY,
    SYMBOL VARCHAR(255) UNIQUE NOT NULL,
    NAME VARCHAR(255),
    DATE DATE,
    IS_ENABLED BOOLEAN
);

CREATE TABLE IF NOT EXISTS QUOTE (
    ID SERIAL PRIMARY KEY,
    SYMBOL VARCHAR(255),
    LATEST_PRICE DOUBLE PRECISION,
    LATEST_UPDATE TIMESTAMP,
    VOLUME BIGINT,
    PREVIOUS_VOLUME BIGINT,
    CHANGE DOUBLE PRECISION,
    CALCULATION_PRICE VARCHAR(255),
    COMPANY_NAME VARCHAR(255),
    CURRENCY VARCHAR(50),
    CONSTRAINT FK_SYMBOL FOREIGN KEY (SYMBOL) REFERENCES SYMBOL(SYMBOL)
);

CREATE INDEX IF NOT EXISTS SYMBOL_IDX ON QUOTE(SYMBOL);